[build]
  base      = ""
  publish   = "public"
  functions = "netlify/functions"
  command   = ""

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/fixtures"
  to   = "/.netlify/functions/fixtures"
  status = 200

[[redirects]]
  from = "/api/results"
  to   = "/.netlify/functions/results"
  status = 200

[[redirects]]
  from = "/api/live"
  to   = "/.netlify/functions/live"
  status = 200

[[redirects]]
  from = "/api/detail"
  to   = "/.netlify/functions/detail"
  status = 200

[[redirects]]
  from = "/api/status"
  to   = "/.netlify/functions/status"
  status = 200

[[redirects]]
  from = "/fixtures"
  to   = "/.netlify/functions/fixtures"
  status = 200

[[redirects]]
  from = "/results"
  to   = "/.netlify/functions/results"
  status = 200

[[redirects]]
  from = "/live"
  to   = "/.netlify/functions/live"
  status = 200

[[redirects]]
  from = "/detail/*"
  to   = "/.netlify/functions/detail?id=:splat"
  status = 200

[[redirects]]
  from = "/status"
  to   = "/.netlify/functions/status"
  status = 200

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
